### ISSUE TITLE
Update to reflect autotag move

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/action-autotag#8]
Autotag now redirects to https://github.com/autotag-dev/autotag/

Action still works, but could be updated in a few places.

**Comment by jazzsequence** [comment]
Where should it be updated? I looked at this a while ago and I didn't see anywhere that we were specifically linking to the old location.

**Comment by pwtyler** [comment]
Readme and right menu

**Comment by jazzsequence** [comment]
closed in #9
